{% set name = "arabic-reshaper" %}
{% set pypi_name = "arabic_reshaper" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/arabic_reshaper-{{ version }}.tar.gz
  sha256: e84b3b0ad8eae395641c94d3010b53bfed2c2b1ab80f25eb8cdc01019ddf6426

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[with-fonttools] -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - configparser  # [py<3]
    - future

test:
  imports:
    - arabic_reshaper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mpcabd/python-arabic-reshaper/
  summary: Reconstruct Arabic sentences to be used in applications that don't support Arabic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mpcabd
